package org.jds.edgar4j.model;

public enum WorkerFailureCode {
    SOURCE_TIMEOUT,
    SOURCE_RATE_LIMITED,
    SOURCE_NOT_FOUND,
    SOURCE_REJECTED,
    NETWORK_UNAVAILABLE,
    POLICY_CHANGED,
    INSUFFICIENT_STORAGE,
    CHECKSUM_MISMATCH,
    CONTENT_INVALID,
    UPLOAD_FAILED,
    LEASE_EXPIRED,
    WORKER_CANCELLED,
    INTERNAL_ERROR
}
